baseURL = "https://unswcpmsoc.com/"
languageCode = "en-us"
title = "UNSW Competitive Programming and Mathematics Society"
theme = "cpmsoc"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 100
